-- db-init.sql for internal exam system (database-first)
-- MySQL 8.0+

CREATE DATABASE IF NOT EXISTS exam_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE exam_system;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS user_account (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(64) NOT NULL DEFAULT '' COMMENT '登录账号（唯一）',
  password_hash VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码哈希',
  password_salt VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码盐',
  display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '姓名',
  mobile_encrypted VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机号密文',
  id_no_encrypted VARCHAR(255) NOT NULL DEFAULT '' COMMENT '证件号密文',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username),
  KEY idx_status (status),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户账号表';

CREATE TABLE IF NOT EXISTS role_dict (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  role_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '角色编码',
  role_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '角色名称',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_role_code (role_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色字典表';

CREATE TABLE IF NOT EXISTS user_role_rel (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  role_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_role (user_id, role_id, is_deleted),
  KEY idx_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关系表';

CREATE TABLE IF NOT EXISTS org_unit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  org_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '组织编码',
  org_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '组织名称',
  parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父组织ID',
  org_level INT NOT NULL DEFAULT 1 COMMENT '层级',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_org_code (org_code),
  KEY idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织架构表';

CREATE TABLE IF NOT EXISTS user_org_rel (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  org_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '组织ID',
  is_primary TINYINT NOT NULL DEFAULT 0 COMMENT '是否主组织:1是0否',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_org (user_id, org_id, is_deleted),
  KEY idx_org_id (org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户组织关系表';

CREATE TABLE IF NOT EXISTS question_bank (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  question_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '题型',
  difficulty VARCHAR(16) NOT NULL DEFAULT '' COMMENT '难度',
  stem VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '题干',
  analysis_text VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '解析',
  score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '分值',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1可用0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_type_difficulty (question_type, difficulty),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题库主表';

CREATE TABLE IF NOT EXISTS question_option (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  question_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '题目ID',
  option_key VARCHAR(8) NOT NULL DEFAULT '' COMMENT '选项键',
  option_text VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '选项内容',
  is_correct TINYINT NOT NULL DEFAULT 0 COMMENT '是否正确答案',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_question_id (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题目选项表';

CREATE TABLE IF NOT EXISTS tag_dict (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  tag_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '标签编码',
  tag_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '标签名称',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tag_code (tag_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签字典表';

CREATE TABLE IF NOT EXISTS question_tag_rel (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  question_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '题目ID',
  tag_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '标签ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_question_tag (question_id, tag_id, is_deleted),
  KEY idx_tag_id (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题目标签关系表';

CREATE TABLE IF NOT EXISTS exam_template (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  template_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '模板名称',
  pass_score DECIMAL(18,4) NOT NULL DEFAULT 60.0000 COMMENT '及格线',
  duration_minutes INT NOT NULL DEFAULT 60 COMMENT '考试时长(分钟)',
  start_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '开始时间',
  end_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '结束时间',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本号',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态:0草稿1已发布2停用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_template_version (template_name, version_no, is_deleted),
  KEY idx_status_time (status, start_time, end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考试模板表';

CREATE TABLE IF NOT EXISTS exam_template_rule (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  template_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '模板ID',
  rule_type VARCHAR(16) NOT NULL DEFAULT '' COMMENT '规则类型:fixed/random',
  question_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '题型',
  difficulty VARCHAR(16) NOT NULL DEFAULT '' COMMENT '难度',
  question_count INT NOT NULL DEFAULT 0 COMMENT '题量',
  fixed_question_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '固定题ID(非固定时为0)',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_template_id (template_id),
  KEY idx_rule_type (rule_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板组卷规则表';

CREATE TABLE IF NOT EXISTS exam_session (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  template_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '模板ID',
  session_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '场次名称',
  session_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '场次状态',
  publish_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '发布时间',
  result_publish_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '成绩发布时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_template_id (template_id),
  KEY idx_session_status (session_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考试场次表';

CREATE TABLE IF NOT EXISTS exam_session_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场次ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  assign_status TINYINT NOT NULL DEFAULT 0 COMMENT '分配状态:0未开始1进行中2已完成',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_session_user (session_id, user_id, is_deleted),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场次考生分配表';

CREATE TABLE IF NOT EXISTS exam_paper_question (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场次ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  question_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '题目ID',
  question_order INT NOT NULL DEFAULT 0 COMMENT '题目序号',
  score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '题目分值',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_session_user (session_id, user_id),
  KEY idx_question_id (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='试卷题目快照表';

CREATE TABLE IF NOT EXISTS answer_sheet (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场次ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  sheet_status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '答卷状态',
  start_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '开始答题时间',
  submit_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '交卷时间',
  auto_score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '自动评分',
  review_score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '复核评分',
  final_score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '最终得分',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_session_user (session_id, user_id, is_deleted),
  KEY idx_sheet_status (sheet_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='答卷主表';

CREATE TABLE IF NOT EXISTS answer_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  sheet_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '答卷ID',
  question_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '题目ID',
  answer_content VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '作答内容',
  is_correct TINYINT NOT NULL DEFAULT 0 COMMENT '是否正确',
  score DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '得分',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_sheet_id (sheet_id),
  KEY idx_question_id (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='答卷明细表';

CREATE TABLE IF NOT EXISTS anti_cheat_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场次ID',
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  event_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '事件类型',
  event_detail VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '事件详情',
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_session_user_time (session_id, user_id, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='防作弊事件表';

CREATE TABLE IF NOT EXISTS review_task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  sheet_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '答卷ID',
  reviewer_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '复核人ID',
  task_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
  review_comment VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '复核意见',
  review_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '复核时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_reviewer_status (reviewer_id, task_status),
  KEY idx_sheet_id (sheet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主观题复核任务表';

CREATE TABLE IF NOT EXISTS result_publish (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '场次ID',
  sheet_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '答卷ID',
  publish_status VARCHAR(16) NOT NULL DEFAULT 'PREPARED' COMMENT '发布状态',
  published_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '发布时间',
  publisher_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发布人ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sheet_publish (sheet_id, is_deleted),
  KEY idx_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成绩发布记录表';

CREATE TABLE IF NOT EXISTS certificate (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  sheet_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '答卷ID',
  certificate_no VARCHAR(64) NOT NULL DEFAULT '' COMMENT '证书编号',
  certificate_status TINYINT NOT NULL DEFAULT 1 COMMENT '证书状态:1有效0失效',
  issued_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '发证时间',
  file_url VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '证书文件地址',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_certificate_no (certificate_no),
  KEY idx_sheet_id (sheet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子证书表';

CREATE TABLE IF NOT EXISTS audit_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  event_domain VARCHAR(32) NOT NULL DEFAULT '' COMMENT '事件域',
  event_action VARCHAR(64) NOT NULL DEFAULT '' COMMENT '事件动作',
  operator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID',
  target_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '目标ID',
  event_payload VARCHAR(4000) NOT NULL DEFAULT '' COMMENT '事件载荷',
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_domain_time (event_domain, event_time),
  KEY idx_operator_time (operator_id, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审计事件表'
PARTITION BY RANGE (TO_DAYS(event_time)) (
  PARTITION p202601 VALUES LESS THAN (TO_DAYS('2026-02-01')),
  PARTITION p202602 VALUES LESS THAN (TO_DAYS('2026-03-01')),
  PARTITION pmax VALUES LESS THAN MAXVALUE
);

CREATE TABLE IF NOT EXISTS export_job (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  job_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '任务类型',
  job_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
  request_payload VARCHAR(4000) NOT NULL DEFAULT '' COMMENT '请求参数',
  requested_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '请求人ID',
  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '请求时间',
  finished_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '完成时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_status_time (job_status, requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导出任务表';

CREATE TABLE IF NOT EXISTS export_file (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  job_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务ID',
  file_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '文件名',
  file_url VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '文件地址',
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文件大小(字节)',
  expire_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '过期时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  created_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记:0否1是',
  deleted_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_job_id (job_id),
  KEY idx_expire_at (expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导出文件表';

-- 字典种子数据
INSERT INTO role_dict (role_code, role_name, sort_no, status, created_by, updated_by)
VALUES
('CANDIDATE', '考生', 10, 1, 0, 0),
('QUESTION_EDITOR', '出题人', 20, 1, 0, 0),
('REVIEWER', '阅卷人', 30, 1, 0, 0),
('ORG_ADMIN', '部门管理员', 40, 1, 0, 0),
('SYS_ADMIN', '系统管理员', 50, 1, 0, 0)
ON DUPLICATE KEY UPDATE role_name = VALUES(role_name), sort_no = VALUES(sort_no), status = VALUES(status), updated_by = VALUES(updated_by);

INSERT INTO tag_dict (tag_code, tag_name, status, created_by, updated_by)
VALUES
('COMPLIANCE', '合规', 1, 0, 0),
('SECURITY', '安全', 1, 0, 0),
('TRAINING', '培训', 1, 0, 0),
('PROMOTION', '晋升', 1, 0, 0)
ON DUPLICATE KEY UPDATE tag_name = VALUES(tag_name), status = VALUES(status), updated_by = VALUES(updated_by);

SET FOREIGN_KEY_CHECKS = 1;
